### ISSUE TITLE
Using "debug" for logging.

### ISSUE THREAD

**Issue by evaisse** [czerwonkabartosz/Micro-Whalla#5]
Hello, 

I think using [debug](https://www.npmjs.com/package/debug) for console will be a good addition.

My current use case involve piping stderr & stdout from a service and there is some console.log that are a bit annoying here. debug is already used by express, it's very convenient to debug some part of the application, without generating to much noise.

Could I make a PR for that ? 

I found you package delightful to use, it's exactly what I was looking for. Great job here.

**Comment by czerwonkabartosz** [comment]
Yes, of course, you could ;) Sorry for the delay but I've had some holidays. I'm going to merge your PR

**Comment by czerwonkabartosz** [comment]
Merged ;)
